/*import { ChatClient } from '@azure/communication-chat';
import { AzureCommunicationTokenCredential } from '@azure/communication-common';

// Your unique Azure Communication service endpoint
let endpointUrl = 'https://acs-shoom-use1-general.unitedstates.communication.azure.com/';
// The user access token generated as part of the pre-requisites
let userAccessToken = 'eyJhbGciOiJSUzI1NiIsImtpZCI6IjYwNUVCMzFEMzBBMjBEQkRBNTMxODU2MkM4QTM2RDFCMzIyMkE2MTkiLCJ4NXQiOiJZRjZ6SFRDaURiMmxNWVZpeUtOdEd6SWlwaGsiLCJ0eXAiOiJKV1QifQ.eyJza3lwZWlkIjoiYWNzOjIyNmY1NWUzLTE1ZTQtNDZhMS04YzNiLTUzZDVkYzJhZjc3Y18wMDAwMDAyMS0xOGZjLTg4MmItMjkwYy0xMTNhMGQwMGZmMmQiLCJzY3AiOjE3OTIsImNzaSI6IjE3MjAwMTg3MjMiLCJleHAiOjE3MjAxMDUxMjMsInJnbiI6ImFtZXIiLCJhY3NTY29wZSI6ImNoYXQiLCJyZXNvdXJjZUlkIjoiMjI2ZjU1ZTMtMTVlNC00NmExLThjM2ItNTNkNWRjMmFmNzdjIiwicmVzb3VyY2VMb2NhdGlvbiI6InVuaXRlZHN0YXRlcyIsImlhdCI6MTcyMDAxODcyM30.diWaA0LTxHo4960GFxqsyQ_NDhiHwG27kM_tU81HY71ysEq-F8VcCBUV3NYaW469roSR3lIpXjMTRWc9yIo-Z_r0pNYOUexAXzuf1OLMc0m29aA609Evy8v4jdr2LxIJzg6TMjiS7l2HBCXmsbGZMzrZVNGnL6RAvWi9nqWFNWgAQHR2N08XHOwLc0wtEU39IR2WHhnyenSoGiXpa3LeER2OyNIrqQRu3DyfzBH0bfqJaeQ_6SWeb0q6JaYXDHGeygQWmQ9x2Oyucs9lyk5Q7mvMGSH0hQ_CdfMqIyWIRVNAf8Oz9eDPSy_RxJOzaVeB_hILCWjMVlRrCo1TZ5ICxQ';

let chatClient = new ChatClient(endpointUrl, new AzureCommunicationTokenCredential(userAccessToken));
console.log('Azure Communication Chat client created!');*/
